apiVersion: v1
kind: Pod
metadata:
  name: employees
  namespace: clo835
  labels:
    app: employees
spec:
  containers:
  - name: employees
    image: 138098912972.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment1-app:latest
    env:
    - name: DBHOST
      value: "mysql"   
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DATABASE
      value: "employees"
    - name: DBPWD
      value: "pw"
    - name: APP_COLOR
      value: "blue"
    ports:
    - containerPort: 8080
  imagePullSecrets:
    - name: regcred