apiVersion: v1
kind: Pod
metadata:
  name: mysql-db
  namespace: clo835
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 138098912972.dkr.ecr.us-east-1.amazonaws.com/clo835-assignment1-db:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"
    ports:
    - containerPort: 3306
  imagePullSecrets:
    - name: regcred