name: Deploy to ECR
# updated ECR Repo week3-1 01/22
on: 
  push:
    branches: [ main ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: Build, test, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        DB_REPOSITORY: clo835-assignment1-db
        APP_REPOSITORY: clo835-assignment1-app
        IMAGE_TAG: latest
      run: |
        # mysql image build and push 
        docker build -t $ECR_REGISTRY/$DB_REPOSITORY:$IMAGE_TAG -f Dockerfile_mysql .
        docker push $ECR_REGISTRY/$DB_REPOSITORY:$IMAGE_TAG
        # application image build and push
        docker build -t $ECR_REGISTRY/$APP_REPOSITORY:$IMAGE_TAG -f Dockerfile .
        docker push $ECR_REGISTRY/$APP_REPOSITORY:$IMAGE_TAG
